# Generated by Django 4.0.3 on 2022-04-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishgrammar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_of_products',
            new_name='sentence',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
