# Generated by Django 4.0.3 on 2022-04-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishgrammar', '0002_rename_num_of_products_product_sentence_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
