# Generated by Django 4.0.3 on 2022-04-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishgrammar', '0005_rename_sentence_post_noun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
