# Generated by Django 4.0.3 on 2022-04-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishgrammar', '0006_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='verb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='noun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
