# Generated by Django 4.0.3 on 2022-04-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishgrammar', '0007_post_verb_alter_post_noun'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adjective',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='adverb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='article',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='preposition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pronoun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
