# Generated by Django 4.0.3 on 2022-04-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishgrammar', '0008_post_adjective_post_adverb_post_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nounphase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='prepphase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sentence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='verbphase',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
