# Generated by Django 4.0.3 on 2022-04-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishgrammar', '0011_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
