# Generated by Django 4.0.3 on 2022-04-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishgrammar', '0012_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interjection',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
